In [2]:
from spamfilter import spamfilter
from trainspamfilter import trainspamfilter
from valsplit import valsplit

from scipy import io
import numpy as np

from checkgradLogistic import checkgradLogistic
from checkgradHingeAndRidge import checkgradHingeAndRidge

from ridge import ridge
from hinge import hinge
from logistic import logistic

# load the data:
data = io.loadmat('data/data_train.mat')
X = data['X']
Y = data['Y']

In [3]:
xTr,xTv,yTr,yTv = valsplit(X,Y)
#xTr:d*n
#yTr:1*n

In [6]:
xTr


array([[0.00144509, 0.        , 0.        , ..., 0.00316456, 0.        ,
        0.        ],
       [0.        , 0.        , 0.00037293, ..., 0.        , 0.        ,
        0.        ],
       [0.00578035, 0.        , 0.00205109, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00578035, 0.        , 0.00018646, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00212766, 0.00018646, ..., 0.        , 0.        ,
        0.00381679],
       [0.        , 0.        , 0.00037293, ..., 0.        , 0.        ,
        0.        ]])

In [4]:
small_step = 1e-5
feature_vector = np.zeros((xTr.shape[0],1)) 
lambdaa = 10

w=feature_vector

In [21]:
case

array([[ True,  True,  True, ...,  True,  True,  True]])

In [33]:
loss = (wx_y).dot(wx_y.transpose()) + lambdaa * (w.transpose().dot(w))

In [53]:
from spamfilter import spamfilter
from trainspamfilter import trainspamfilter
from valsplit import valsplit

from scipy import io
import numpy as np

from checkgradLogistic import checkgradLogistic
from checkgradHingeAndRidge import checkgradHingeAndRidge

from ridge import ridge
from hinge import hinge
from logistic import logistic

# load the data:
data = io.loadmat('data/data_train.mat')
X = data['X']
Y = data['Y']

# split the data:
xTr,xTv,yTr,yTv = valsplit(X,Y)

# uncomment checkgrad for a function to check that gradients are implemented correctly
# error should be very low (under 1e-8 for defualt parameters)

small_step = 1e-5
feature_vector = np.zeros((xTr.shape[0],1))
lambdaa = 10

gradient = ridge(feature_vector, xTr, yTr, lambdaa)

NameError: name 'loss' is not defined

In [35]:
loss[0]

array([4000.])

In [52]:
from ridge import ridge
from checkgradHingeAndRidge import checkgradHingeAndRidge
ridge_error = checkgradHingeAndRidge(ridge, feature_vector, small_step, xTr, yTr, lambdaa)

NameError: name 'loss' is not defined

In [51]:
loss[0][0]

4000.0

In [6]:
xTr[0][0:5]

array([0.00144509, 0.        , 0.        , 0.00104275, 0.        ])

In [9]:
import math
math.exp(xTr[0][0])

1.0014461313461334

In [7]:
fuck=np.array([[1,2,3],[1,2,3]])
fuck2=np.array([[1.2,2.4,3.6]])

In [8]:
fuck2*fuck

array([[ 1.2,  4.8, 10.8],
       [ 1.2,  4.8, 10.8]])

In [5]:
multiplier=yTr*np.dot(w.transpose(),xTr)

In [6]:
multiplier.shape

(1, 4000)

In [7]:
loss=np.sum(np.log(1+np.exp(-multiplier)))

In [8]:
loss

2772.5887222397814

In [9]:
gradient=np.sum(-xTr*yTr/(1+np.exp(multiplier)),axis=1)

In [10]:
gradient.shape

(1024,)

In [11]:
w.shape

(1024, 1)

In [12]:
gradient

array([ 0.16041617,  0.13401081,  0.23780817, ..., -0.07143565,
        1.72155223,  0.20639352])

In [21]:
iwks=-xTr*yTr/(1+np.exp(multiplier))

In [22]:
iwks.shape

(1024, 4000)

In [23]:
iwks.sum(axis=1).reshape(1024,1)

array([[ 0.16041617],
       [ 0.13401081],
       [ 0.23780817],
       ...,
       [-0.07143565],
       [ 1.72155223],
       [ 0.20639352]])

In [25]:
judge=1-yTr*np.dot(w.transpose(),xTr)
af_judge=np.maximum(judge,np.zeros((1,yTr.shape[1])))
loss=af_judge.sum()+np.dot(w.transpose(),w)*lambdaa
case=(judge>0)
gradient=2*lambdaa*w-np.dot(xTr,(yTr*case).transpose())

In [26]:
gradient.shape

(1024, 1)