In [21]:
import scipy.io as sio
import numpy as np
bostonData = sio.loadmat('./boston.mat')

In [22]:
xTr = bostonData['xTr']
xTe = bostonData['xTe']

In [19]:
d, n = np.shape(xTr)
D, N = np.shape(xTe)
## << Remove 2 lines above and insert your solution here

m = np.mean(xTr,axis=1)
M = np.mat(m)
u = np.diag(1/np.std(xTr.T,axis=0))
xTr = u.dot((xTr-np.tile(M.T,n)))
xTe = u.dot((xTe-np.tile(M.T,N)))
xTr = np.array(xTr)
xTe = np.array(xTe)

In [20]:
print(xTr)
print(xTe)
print(u)
print(m)

[[-4.19594397e-01  1.36356042e+00 -3.88646360e-01 ... -4.18194288e-01
  -3.89874246e-01 -4.43216824e-02]
 [ 1.71251147e+00 -4.81479001e-01 -4.81479001e-01 ... -4.81479001e-01
  -4.81479001e-01 -4.81479001e-01]
 [-8.83809370e-01  9.73473953e-01  1.52426455e+00 ... -1.00443106e+00
  -2.18210183e-01  9.73473953e-01]
 ...
 [-8.38423368e-01  7.92380632e-01  1.24538174e+00 ...  2.22787432e-02
  -2.30213680e-02  7.92380632e-01]
 [ 4.44518698e-01  4.44518698e-01  3.53932196e-01 ...  4.34478050e-01
   3.76109890e-01  4.05569812e-01]
 [-7.73731716e-01  2.42170100e+00  2.91412522e-01 ... -1.53589333e-03
   7.36910112e-01  2.00963011e-01]]
[[-0.40165451 -0.41807309 -0.42207462 ... -0.04790116 -0.38036584
  -0.41719391]
 [-0.481479   -0.481479    3.27964751 ... -0.481479   -0.481479
   0.35432689]
 [ 2.37442945 -1.16138458 -1.11197328 ...  1.18855841 -0.75592132
  -1.17301076]
 ...
 [ 0.74708052 -0.29482203 -1.15552415 ... -1.69912548 -0.47602248
  -1.60852526]
 [-0.42129407  0.43525041  0.32800305

In [23]:
d, n = np.shape(xTr)
m = np.mean(xTr, axis=1).reshape(d,1)
u = np.diag(1./np.std(xTr, axis=1))
xTr = np.dot(u, xTr - m)
xTe = np.dot(u, xTe - m) 

In [24]:
print(xTr)
print(xTe)
print(u)
print(m)

[[-4.19594397e-01  1.36356042e+00 -3.88646360e-01 ... -4.18194288e-01
  -3.89874246e-01 -4.43216824e-02]
 [ 1.71251147e+00 -4.81479001e-01 -4.81479001e-01 ... -4.81479001e-01
  -4.81479001e-01 -4.81479001e-01]
 [-8.83809370e-01  9.73473953e-01  1.52426455e+00 ... -1.00443106e+00
  -2.18210183e-01  9.73473953e-01]
 ...
 [-8.38423368e-01  7.92380632e-01  1.24538174e+00 ...  2.22787432e-02
  -2.30213680e-02  7.92380632e-01]
 [ 4.44518698e-01  4.44518698e-01  3.53932196e-01 ...  4.34478050e-01
   3.76109890e-01  4.05569812e-01]
 [-7.73731716e-01  2.42170100e+00  2.91412522e-01 ... -1.53589333e-03
   7.36910112e-01  2.00963011e-01]]
[[-0.40165451 -0.41807309 -0.42207462 ... -0.04790116 -0.38036584
  -0.41719391]
 [-0.481479   -0.481479    3.27964751 ... -0.481479   -0.481479
   0.35432689]
 [ 2.37442945 -1.16138458 -1.11197328 ...  1.18855841 -0.75592132
  -1.17301076]
 ...
 [ 0.74708052 -0.29482203 -1.15552415 ... -1.69912548 -0.47602248
  -1.60852526]
 [-0.42129407  0.43525041  0.32800305

array([[0, 2, 3],
       [4, 5, 6]])

array([[-4.19594397e-01,  1.36356042e+00, -3.88646360e-01, ...,
        -4.18194288e-01, -3.89874246e-01, -4.43216824e-02],
       [ 1.71251147e+00, -4.81479001e-01, -4.81479001e-01, ...,
        -4.81479001e-01, -4.81479001e-01, -4.81479001e-01],
       [-8.83809370e-01,  9.73473953e-01,  1.52426455e+00, ...,
        -1.00443106e+00, -2.18210183e-01,  9.73473953e-01],
       ...,
       [-8.38423368e-01,  7.92380632e-01,  1.24538174e+00, ...,
         2.22787432e-02, -2.30213680e-02,  7.92380632e-01],
       [ 4.44518698e-01,  4.44518698e-01,  3.53932196e-01, ...,
         4.34478050e-01,  3.76109890e-01,  4.05569812e-01],
       [-7.73731716e-01,  2.42170100e+00,  2.91412522e-01, ...,
        -1.53589333e-03,  7.36910112e-01,  2.00963011e-01]])

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])