In [3]:
import numpy as np
from computeK import computeK
from generateQP import generateQP
from recoverBias import recoverBias
from cvxopt import solvers
from createsvmclassifier import createsvmclassifier

In [4]:
xTr = np.genfromtxt('xTr.csv', delimiter=',')
yTr = np.genfromtxt('yTr.csv', delimiter=',').reshape((xTr.shape[1], 1))

In [100]:
C = 1
P = 1
ktype='rbf'

In [114]:
K = computeK(ktype, xTr, xTr, P)

#print("Generate QP...")
Q, p, G, h, A, b = generateQP(K, yTr, C)

#print("solve QP")
solvers.options['show_progress'] = False
sol = solvers.qp(Q, p, G, h, A, b)
#print('Solution status:', sol['status'])
alphas = np.array(sol['x'])

In [120]:
combine = (C-alphas)*alphas
maxCom = np.max(combine)
index = np.where(combine == maxCom)
index = int(index[0])
bias = yTr[index] - K[:,index].dot(alphas*yTr)
print(bias)

[0.35627398]


In [119]:
alphas.shape

(100, 1)

In [97]:
sv

90

In [50]:
second

array([[170, 208, 250, 296],
       [170, 208, 250, 296],
       [170, 208, 250, 296]])

In [52]:
np.exp(second)

array([[6.76179381e+073, 2.15403242e+090, 3.74645461e+108,
        3.55767804e+128],
       [6.76179381e+073, 2.15403242e+090, 3.74645461e+108,
        3.55767804e+128],
       [6.76179381e+073, 2.15403242e+090, 3.74645461e+108,
        3.55767804e+128]])

In [1]:
i=0
testSize=20
n=100

In [1]:
from l2distance import l2distance

In [5]:
l2distance(xTr,xTr)

array([[0.        , 2.71097826, 4.82300604, ..., 2.86937569, 2.83622939,
        1.39963769],
       [2.71097826, 0.        , 7.02280809, ..., 5.20670596, 2.12490909,
        2.65708912],
       [4.82300604, 7.02280809, 0.        , ..., 1.95852113, 5.62508913,
        6.09025514],
       ...,
       [2.86937569, 5.20670596, 1.95852113, ..., 0.        , 4.13308067,
        4.13612832],
       [2.83622939, 2.12490909, 5.62508913, ..., 4.13308067, 0.        ,
        3.70121623],
       [1.39963769, 2.65708912, 6.09025514, ..., 4.13612832, 3.70121623,
        0.        ]])